### ISSUE TITLE
Remote Stream Wrapper Security issue

### ISSUE THREAD

**Issue by kimlop** [openeuropa/media_avportal#76]
are you aware that the required "Remote Stream Wrapper" module has a security problem?

https://www.drupal.org/project/remote_stream_wrapper

**Comment by vaidas-astrovas-eeas** [comment]
Adding reference to issue in DO: https://www.drupal.org/project/remote_stream_wrapper/issues/3260802

**Comment by brummbar** [comment]
It was marked as "resolved" since it's not really an issue of the module https://www.drupal.org/sa-contrib-2022-020 .
