### ISSUE TITLE
Problem using module from European Commission DNS

### ISSUE THREAD

**Issue by dhamaris** [openeuropa/media_avportal#95]
Dear team,
 
We are facing an issue when trying to use your module in the external network of the European Commission because in your module there is a validation endpoint: https://gfdwwnbuul.execute-api.eu-west-1.amazonaws.com/avsportal/avsportal.
 
The issue here is that the European Commission network blocks external URLs so we can't reach the endpoint due to not having a standard European Commission DNS (for example: europa.eu or ec.europa.eu)
 
Do you plan modifying the DNS [https://gfdwwnbuul.execute-api.eu-west-1.amazonaws.com](https://gfdwwnbuul.execute-api.eu-west-1.amazonaws.com/av) to match the European Commission DNS pattern at some point?
 
Thanks!

**Comment by brummbar** [comment]
Hello @dhamaris , we are not in control of the API endpoints, we only created a module that connects to the existing service.
The API url is the same that is used on https://audiovisual.ec.europa.eu/en/ , you can check the console to see the requests it makes, so it is up to date.
It's best that you contact the AV portal team to know if they have a solution or ask the team that handles your infrastructure to add an exception.

**Comment by dhamaris** [comment]
Thanks for your help @brummbar, in the end we added an exception to the whitelist on LISO so that it would allow requests to that domain [https://gfdwwnbuul.execute-api.eu-west-1.amazonaws.com](https://gfdwwnbuul.execute-api.eu-west-1.amazonaws.com/avsportal/avsportal)
I close this ticket
