### ISSUE TITLE
Release 1.7 should be locked to Drupal ^10.3

### ISSUE THREAD

**Issue by Aporie** [openeuropa/media_avportal#97]
Hi guys,

In 1.7 you've introduced this patch: https://github.com/openeuropa/media_avportal/pull/94/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R48
The patch locks remote_stream_wrapper to D10.3. By dependency, media_avportal should also been locked to D10.3 to avoid conflicts such as this one:

![image](https://github.com/openeuropa/media_avportal/assets/3462591/abf91ec0-2775-4cfe-88ce-e06072e8eca9)

As quick fix for other devs having this issue, lock media_av_portal to 1.6.

**Comment by brummbar** [comment]
We added a message in the patch name to point out how to use that release with 10.2 
```
"Drupal 10.3.x only - see media_avportal/README.md for 10.2.x - https://www.drupal.org/project/remote_stream_wrapper/issues/3437974"
```
